# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.cache/wt [current_project]
set_property parent.project_path /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  /home/corvo/Learning/verilog/SOC/CPU/IPModule/CPU-Core
  /home/corvo/Learning/verilog/Oh-My-Core
  /home/corvo/Learning/verilog/SOC/CPU/IPModule/Teacher-Core
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
set_property is_locked true [get_files /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top dist_mem_gen_0 -part xc7a100tcsg324-1 -mode out_of_context
rename_ref -prefix_all dist_mem_gen_0_
write_checkpoint -noxdef dist_mem_gen_0.dcp
catch { report_utilization -file dist_mem_gen_0_utilization_synth.rpt -pb dist_mem_gen_0_utilization_synth.pb }
if { [catch {
  write_verilog -force -mode synth_stub /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.runs/dist_mem_gen_0_synth_1/dist_mem_gen_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.runs/dist_mem_gen_0_synth_1/dist_mem_gen_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.runs/dist_mem_gen_0_synth_1/dist_mem_gen_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.runs/dist_mem_gen_0_synth_1/dist_mem_gen_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
add_files /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.runs/dist_mem_gen_0_synth_1/dist_mem_gen_0_stub.v -of_objects [get_files /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci]
add_files /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.runs/dist_mem_gen_0_synth_1/dist_mem_gen_0_stub.vhdl -of_objects [get_files /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci]
add_files /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.runs/dist_mem_gen_0_synth_1/dist_mem_gen_0_sim_netlist.v -of_objects [get_files /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci]
add_files /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.runs/dist_mem_gen_0_synth_1/dist_mem_gen_0_sim_netlist.vhdl -of_objects [get_files /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci]
add_files /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.runs/dist_mem_gen_0_synth_1/dist_mem_gen_0.dcp -of_objects [get_files /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci]

if {[file isdir /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.ip_user_files/ip/dist_mem_gen_0]} {
  catch { 
    file copy -force /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.runs/dist_mem_gen_0_synth_1/dist_mem_gen_0_sim_netlist.v /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.ip_user_files/ip/dist_mem_gen_0
  }
}

if {[file isdir /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.ip_user_files/ip/dist_mem_gen_0]} {
  catch { 
    file copy -force /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.runs/dist_mem_gen_0_synth_1/dist_mem_gen_0_sim_netlist.vhdl /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.ip_user_files/ip/dist_mem_gen_0
  }
}

if {[file isdir /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.ip_user_files/ip/dist_mem_gen_0]} {
  catch { 
    file copy -force /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.runs/dist_mem_gen_0_synth_1/dist_mem_gen_0_stub.v /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.ip_user_files/ip/dist_mem_gen_0
  }
}

if {[file isdir /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.ip_user_files/ip/dist_mem_gen_0]} {
  catch { 
    file copy -force /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.runs/dist_mem_gen_0_synth_1/dist_mem_gen_0_stub.vhdl /home/corvo/Learning/verilog/SOC-Pro/Old-Cpu/Old-Cpu.ip_user_files/ip/dist_mem_gen_0
  }
}
