# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.cache/wt [current_project]
set_property parent.project_path /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/corvo/Learning/verilog/CPU-Core [current_project]
add_files /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.srcs/sources_1/bd/top_bd/ip/top_bd_dist_mem_gen_0_0/prgmip32.coe
add_files /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.srcs/sources_1/imports/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.srcs/dmem32.coe
add_files /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.srcs/sources_1/imports/verilog/MyCoe/prgmip32.coe
add_files /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.srcs/sources_1/imports/verilog/MyCoe/dmem32.coe
add_files /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.srcs/sources_1/imports/verilog/MyCoe/test_prgmip32.coe
add_files /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.srcs/sources_1/imports/verilog/MyCoe/test_dmem32.coe
add_files /home/corvo/Learning/MyCoe/test_prgmip32.coe
add_files /home/corvo/Learning/MyCoe/test_dmem32.coe
add_files /home/corvo/Learning/verilog/CourseSubmit/测试程序/斐波那契数列测试/prgmip32.coe
add_files /home/corvo/Learning/verilog/CourseSubmit/测试程序/斐波那契数列测试/dmem32.coe
read_verilog -library xil_defaultlib /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.srcs/sources_1/new/alu_impl.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top alu_impl -part xc7a100tcsg324-1


write_checkpoint -force -noxdef alu_impl.dcp

catch { report_utilization -file alu_impl_utilization_synth.rpt -pb alu_impl_utilization_synth.pb }
