# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/corvo/Learning/verilog/SOC/CPU/Citrus/Citrus.srcs/sources_1/ip/dist_mem_gen_ram/dist_mem_gen_ram.xci
# IP: The module: 'dist_mem_gen_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/corvo/Learning/verilog/SOC/CPU/Citrus/Citrus.srcs/sources_1/ip/dist_mem_gen_ram/dist_mem_gen_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/corvo/Learning/verilog/SOC/CPU/Citrus/Citrus.srcs/sources_1/ip/dist_mem_gen_ram/dist_mem_gen_ram.xci
# IP: The module: 'dist_mem_gen_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/corvo/Learning/verilog/SOC/CPU/Citrus/Citrus.srcs/sources_1/ip/dist_mem_gen_ram/dist_mem_gen_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
