# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.cache/wt [current_project]
set_property parent.project_path /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  /home/corvo/Learning/verilog/CourseSubmit/IPModule/Teacher-Core
  /home/corvo/Learning/verilog/CourseSubmit/IPModule/CPU-Core
} [current_project]
read_ip -quiet /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.srcs/sources_1/ip/orgate_0/orgate_0.xci
set_property is_locked true [get_files /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.srcs/sources_1/ip/orgate_0/orgate_0.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top orgate_0 -part xc7a100tcsg324-1 -mode out_of_context

rename_ref -prefix_all orgate_0_

write_checkpoint -force -noxdef orgate_0.dcp

catch { report_utilization -file orgate_0_utilization_synth.rpt -pb orgate_0_utilization_synth.pb }

if { [catch {
  file copy -force /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.runs/orgate_0_synth_1/orgate_0.dcp /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.srcs/sources_1/ip/orgate_0/orgate_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.srcs/sources_1/ip/orgate_0/orgate_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.srcs/sources_1/ip/orgate_0/orgate_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.srcs/sources_1/ip/orgate_0/orgate_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.srcs/sources_1/ip/orgate_0/orgate_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.ip_user_files/ip/orgate_0]} {
  catch { 
    file copy -force /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.srcs/sources_1/ip/orgate_0/orgate_0_stub.v /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.ip_user_files/ip/orgate_0
  }
}

if {[file isdir /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.ip_user_files/ip/orgate_0]} {
  catch { 
    file copy -force /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.srcs/sources_1/ip/orgate_0/orgate_0_stub.vhdl /home/corvo/Learning/verilog/CourseSubmit/Oh-My-Project/Oh-My-Project.ip_user_files/ip/orgate_0
  }
}
